language: java
jdk:
  - openjdk6
  - openjdk7
before_install:
  - echo $PWD
  - sudo apt-get install tomcat6
install: 
  - ant build
notifications:
  email:
    recipients:
      - brucellino@gmail.com
      - Marco.Fargetta@ct.infn.it
